
version: "3.9"
services:
  web:
    build: .
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
volumes:
  logvolume01: {}
